export const EGYPT_BANKS = [
  'National Bank of Egypt',
  'Banque Misr',
  'Banque du Caire',
  'Bank of Alexandria',
  'Commercial International Bank (CIB)',
  'QNB Al Ahli',
  'Arab African International Bank',
  'Arab Bank',
  'Arab International Bank',
  'Attijariwafa Bank Egypt',
  'Crédit Agricole Egypt',
  'Citibank Egypt',
  'aiBANK',
  'Export Development Bank of Egypt',
  'Faisal Islamic Bank of Egypt',
  'HSBC Egypt',
  'Housing and Development Bank',
  'National Bank of Kuwait Egypt',
  'SAIB',
  'Suez Canal Bank',
  'The United Bank',
  'Al Baraka Bank Egypt',
  'Abu Dhabi Commercial Bank Egypt',
  'First Abu Dhabi Bank Misr',
  'Emirates NBD Egypt',
  'Mashreq Bank Egypt',
  'Ahli United Bank Egypt',
  'Al Ahli Bank of Kuwait Egypt',
  'Egyptian Arab Land Bank',
  'EG Bank',
  'Abu Dhabi Islamic Bank Egypt',
  'Agricultural Bank of Egypt',
  'Industrial Development Bank',
  'Egyptian Gulf Bank',
  'Bank ABC Egypt',
  'Kuwait Finance House Egypt',
  'Arab Investment Bank',
  'onebank',
];
